participants
participant01

PaperExperiment2 new runForClasses:{ 
		{ BitmapCharacterSet . CharacterSet . CharacterSetComplement } .  
		{ FMMultivalueLink . FMNullMultivalueLink } .
		{ WeakHashSet . WeakKeyHashTable } .
		{ IdentityHashSet . WeakKeyIdentityHashTable }
		}. 

PaperExperiment2 new run: { 
#(1 6 8) .
#(16 17) .
#(51 50) .
#(57 58) .
#(60 9) .
#(35 83 66 31) .
#(106 43 67 84 113 104 148) .
#(110 59 109 41) .
#(24 38) .
#(55 56) .
#(127 144 130 )
}. 
