participants
participant12


PaperExperiment2 new runForClasses: { 
{ BitmapCharacterSet . CharacterSet  . CharacterSetComplement } .
{ FLLargeIdentitySet . FLLargeIdentityDictionary } 
}. 

PaperExperiment2 new run: { 
#(52 55 56 20 143 115 70) .
#(45 3 2) .
#(144 130) .
#(118 81 83) .
#(57 58) .
#(46 47) .
#(50 51) .
#(48 49) .
#(12 126 95 18 69) .
#(94 125) .
#(139 74) .
#(105 103) .
#(59 41 109 110) .
#(144 130)
}. 
