participants
participant08


PaperExperiment2 new runForClasses: { 
{ CharacterSet . CharacterSetComplement  } .
{ IdentityHashTable . IdentityHashSet } .
{ MalDendrogramLeaf . MalDendrogramNode } .
{ MalNameMapping . MalNumberMapping } .
{ MooseGroupStorage . MooseGroupRuntimeStorage } .
}. 

PaperExperiment2 new run: { 
#(1 6) .
#(39 22) .
#(109 110) .
#(57 58) .
#(43 104 106) .
#(41 59) .
#(50 51) .
#(105 71) .
#(127 130)
}. 
