participants
participant04


PaperExperiment2 new runForClasses: { 
{ BitmapCharacterSet . CharacterSet . CharacterSetComplement } .
{ FMMultiMultivalueLink . FMNullMultivalueLink } .
{ IdentityHashSet . IdentityHashTable . WeakKeyIdentityHashTable } .
{ MethodDictionary . OCKeyedSet }
}. 

PaperExperiment2 new run: { 
#(31 35) .
#(6 8 ) .
#(38 7 147) .
#(52 55) .
#(15 56) .
#(51 50) .
#(97 30) .
#(39 29 36) .
#(117 18 70) .
#(106 104) .
#(109 110) .
#(46 47 ).
#(48 49)
}. 
