participants
participant06


PaperExperiment2 new runForClasses: { 
{ BitmapCharacterSet . CharacterSet . CharacterSetComplement } .
{ FMMultivalueLink . FMNullMultivalueLink } .
{ HashTable . HashSet } .
{ IdentityHashSet . IdentityHashTable } .
{ WeakHashSet . WeakKeyHashTable }
}. 

PaperExperiment2 new run: { 
#(33 36) .
#(15 20) .
#(48 49) .
#(21 22 37) .
#(6 8) .
#(51 50) .
#(3 19) .
#(46 47) .
#(55 56) .
#(16 17) .
#(43 104 106 ).
#(109 110 ).
#(127 130 ).
#(102 132)
}. 
